export const categories = [
  'Definitions',
  'Section 6',
  'Section 7',
  'Section 2',
  'Model Local Rules',
  'Clarifications',
];

export const wheelValues = [100, 150, 200, 250, 300, 350, 400, 450, 500, 'Bankrupt', 'Lose Turn', 600];

export const questionBank = [
  {
    id: 1,
    category: "Definitions",
    points: 100,
    prompt: "A player sees water on the fairway after heavy rain. Which defined term best fits water that is temporarily visible before or after the player takes a stance?",
    choices: [
      "Temporary water",
      "Penalty area",
      "Ground under repair",
      "Loose impediment",
    ],
    answer: 0,
    citation: "Definition: Temporary Water",
    explanation: "Temporary water is the relevant defined condition when water is temporarily visible on the course outside a penalty area.",
  },
  {
    id: 2,
    category: "Section 6",
    points: 200,
    prompt: "A player starts a hole from just outside the teeing area in stroke play and then corrects the mistake before starting the next hole. What is the normal consequence?",
    choices: [
      "General penalty and the corrected stroke counts",
      "No penalty because it was corrected",
      "Disqualification immediately",
      "One penalty stroke only",
    ],
    answer: 0,
    citation: "Rule 6.1b",
    explanation: "In stroke play, playing from outside the teeing area must be corrected and the player gets the general penalty.",
  },
  {
    id: 3,
    category: "Section 7",
    points: 300,
    prompt: "During a search, a player accidentally moves their own ball. What is the usual outcome under the search Rule?",
    choices: [
      "No penalty, and the ball must be replaced",
      "One penalty stroke and replace",
      "General penalty and play as it lies",
      "No penalty and play from the new spot",
    ],
    answer: 0,
    citation: "Rule 7.4",
    explanation: "There is normally no penalty for accidentally moving a ball while fairly searching, but it must be replaced.",
  },
  {
    id: 4,
    category: "Section 2",
    points: 400,
    prompt: "Who is responsible for deciding the boundaries of the course and marking penalty areas for a competition?",
    choices: [
      "The Committee",
      "Each player",
      "The marker",
      "The first group of the day",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Course setup responsibilities belong to the Committee, including boundaries and penalty area marking.",
  },
  {
    id: 5,
    category: "Model Local Rules",
    points: 500,
    prompt: "Model Local Rule E-5 is most closely connected with which situation?",
    choices: [
      "Alternative to stroke-and-distance for a ball lost outside a penalty area or out of bounds",
      "Free relief from a bunker every time",
      "Automatic preferred lies in all rough",
      "Practising on the course before a round",
    ],
    answer: 0,
    citation: "Model Local Rule E-5",
    explanation: "E-5 provides an alternative relief option for certain lost-ball or out-of-bounds situations when adopted.",
  },
  {
    id: 6,
    category: "Clarifications",
    points: 100,
    prompt: "A Clarification is best used when what is needed?",
    choices: [
      "Extra guidance on applying a Rule to a specific issue",
      "A replacement for the Rules of Golf",
      "Permission to ignore a Rule",
      "A way to avoid Committee decisions",
    ],
    answer: 0,
    citation: "Official Clarifications",
    explanation: "Clarifications help explain particular applications of the Rules but do not replace the Rules themselves.",
  },
  {
    id: 7,
    category: "Definitions",
    points: 200,
    prompt: "Which term describes the whole area of the course except the teeing area of the hole being played, all penalty areas, all bunkers, and the putting green of the hole being played?",
    choices: [
      "General area",
      "Through the green",
      "Course proper",
      "Relief area",
    ],
    answer: 0,
    citation: "Definition: General Area",
    explanation: "The general area is the default area of the course after excluding the specific areas listed in the definition.",
  },
  {
    id: 8,
    category: "Section 6",
    points: 300,
    prompt: "In match play, a player plays from outside the teeing area. What may the opponent do?",
    choices: [
      "Cancel the stroke and require replay from inside the teeing area",
      "Add two penalty strokes",
      "Declare the player disqualified",
      "Require the player to drop in the teeing area",
    ],
    answer: 0,
    citation: "Rule 6.1b",
    explanation: "In match play, the opponent may cancel a stroke made from outside the teeing area.",
  },
  {
    id: 9,
    category: "Section 7",
    points: 400,
    prompt: "A player moves sand while searching for a ball in a bunker and improves the lie after the ball is found. What must the player normally do?",
    choices: [
      "Re-create the original lie as nearly as possible",
      "Play it as improved without penalty",
      "Drop outside the bunker",
      "Declare the ball unplayable",
    ],
    answer: 0,
    citation: "Rule 7.1b",
    explanation: "If conditions are improved during a search, they may need to be restored as nearly as possible.",
  },
  {
    id: 10,
    category: "Section 2",
    points: 500,
    prompt: "Why should a Committee define the course accurately before a competition?",
    choices: [
      "So players know which Rules and relief options apply",
      "So players can choose their own relief areas",
      "So all penalty areas become optional",
      "So match play and stroke play use different boundaries",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Clear course definition helps players apply the correct Rules during the round.",
  },
  {
    id: 11,
    category: "Model Local Rules",
    points: 100,
    prompt: "If Model Local Rule E-5 is not adopted by the Committee, may a player use it anyway?",
    choices: [
      "No",
      "Yes, always",
      "Only in match play",
      "Only if the marker agrees",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8; Model Local Rules",
    explanation: "A Model Local Rule applies only when the Committee has adopted it.",
  },
  {
    id: 12,
    category: "Clarifications",
    points: 200,
    prompt: "If a Rules question is answered directly by the Rule text, what should be consulted first?",
    choices: [
      "The relevant Rule",
      "Social media comments",
      "Only the Clarifications",
      "A player vote",
    ],
    answer: 0,
    citation: "Official Clarifications introduction",
    explanation: "Clarifications are additional guidance; the Rules themselves remain the primary source.",
  },
  {
    id: 13,
    category: "Definitions",
    points: 300,
    prompt: "A ball is resting against a movable rake beside a bunker. What is the rake under the Rules?",
    choices: [
      "Movable obstruction",
      "Loose impediment",
      "Integral object",
      "Boundary object",
    ],
    answer: 0,
    citation: "Definition: Obstruction",
    explanation: "A manufactured object that can be moved with reasonable effort and without damaging the course is normally a movable obstruction.",
  },
  {
    id: 14,
    category: "Section 6",
    points: 400,
    prompt: "When does play of a hole normally begin?",
    choices: [
      "When the player makes a stroke to start the hole",
      "When the player arrives at the tee",
      "When the group ahead leaves the green",
      "When the scorecard is marked",
    ],
    answer: 0,
    citation: "Rule 6.1",
    explanation: "A hole begins when the player makes a stroke to start that hole.",
  },
  {
    id: 15,
    category: "Section 7",
    points: 500,
    prompt: "A player finds a ball but is not sure it is theirs. What may the player do?",
    choices: [
      "Mark and lift it to identify it",
      "Kick it over without marking",
      "Clean it fully and replace it anywhere",
      "Substitute a new ball",
    ],
    answer: 0,
    citation: "Rule 7.3",
    explanation: "A player may lift a ball to identify it after first marking the spot, but cleaning is limited to what is needed.",
  },
  {
    id: 16,
    category: "Section 2",
    points: 100,
    prompt: "A Committee wants to mark an area where play is prohibited. What should it define the area as?",
    choices: [
      "A no play zone connected to an abnormal course condition or penalty area",
      "A bunker",
      "A loose impediment area",
      "An automatic free-drop zone only",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Definition: No Play Zone",
    explanation: "A no play zone must be defined as part of another condition such as an abnormal course condition or penalty area.",
  },
  {
    id: 17,
    category: "Model Local Rules",
    points: 200,
    prompt: "Preferred lies are usually implemented through which mechanism?",
    choices: [
      "A Model Local Rule adopted by the Committee",
      "A player\u2019s choice at any time",
      "An automatic Rule whenever the fairway is wet",
      "A decision by the marker after each shot",
    ],
    answer: 0,
    citation: "Model Local Rule E-3",
    explanation: "Preferred lies require Committee adoption and defined terms such as the area and size of relief.",
  },
  {
    id: 18,
    category: "Clarifications",
    points: 300,
    prompt: "A clarification about practice before a stroke-play round would most likely relate to which Rule area?",
    choices: [
      "Rule 5.2",
      "Rule 18.3",
      "Rule 6.1",
      "Rule 13.2",
    ],
    answer: 0,
    citation: "Clarification 5.2b/3",
    explanation: "Recent clarifications include guidance on practice on the course before a stroke-play round.",
  },
  {
    id: 19,
    category: "Definitions",
    points: 400,
    prompt: "A branch that has fallen from a tree is lying near a player\u2019s ball. What is it?",
    choices: [
      "Loose impediment",
      "Movable obstruction",
      "Ground under repair",
      "Abnormal course condition",
    ],
    answer: 0,
    citation: "Definition: Loose Impediment",
    explanation: "A detached natural object such as a fallen branch is a loose impediment unless it is fixed, growing, embedded, or sticking to the ball.",
  },
  {
    id: 20,
    category: "Section 6",
    points: 500,
    prompt: "A player accidentally plays a wrong ball from the fairway in stroke play. What must the player generally do?",
    choices: [
      "Correct the mistake by playing the right ball and add the general penalty",
      "Continue with the wrong ball without penalty",
      "Replay from the tee with one penalty stroke",
      "Drop where the wrong ball was played",
    ],
    answer: 0,
    citation: "Rule 6.3c",
    explanation: "Playing a wrong ball in stroke play must be corrected, normally with the general penalty.",
  },
  {
    id: 21,
    category: "Section 7",
    points: 100,
    prompt: "Before lifting a ball for identification, what should the player do?",
    choices: [
      "Mark the spot",
      "Announce a provisional ball",
      "Take lateral relief",
      "Ask the Committee for permission every time",
    ],
    answer: 0,
    citation: "Rule 7.3",
    explanation: "The spot should be marked before the ball is lifted for identification.",
  },
  {
    id: 22,
    category: "Section 2",
    points: 200,
    prompt: "Before a competition, the Committee should consider whether Local Rules are needed for what purpose?",
    choices: [
      "To address course conditions or competition needs consistently with the Rules",
      "To let players ignore difficult Rules",
      "To remove all penalties",
      "To change stroke play into match play",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Section 8",
    explanation: "Local Rules may be adopted for appropriate course or competition conditions, but must be consistent with the Rules.",
  },
  {
    id: 23,
    category: "Model Local Rules",
    points: 300,
    prompt: "A Committee wants to allow relief from seams of cut turf. What should it use?",
    choices: [
      "An appropriate Model Local Rule",
      "A verbal announcement only after disputes arise",
      "A player-by-player agreement",
      "The lost ball Rule",
    ],
    answer: 0,
    citation: "Model Local Rules",
    explanation: "Model Local Rules provide approved wording and structure for specific local conditions.",
  },
  {
    id: 24,
    category: "Clarifications",
    points: 400,
    prompt: "Clarifications are incorporated into digital Rules materials for what purpose?",
    choices: [
      "To keep guidance accessible with the Rules",
      "To replace the Committee Procedures",
      "To remove penalties",
      "To make Local Rules automatic",
    ],
    answer: 0,
    citation: "R&A Rules Resources: Additional Clarifications",
    explanation: "Digital Rules materials may include additional clarifications so users can find current guidance.",
  },
  {
    id: 25,
    category: "Definitions",
    points: 500,
    prompt: "Which phrase describes where a ball must be dropped and come to rest when a player takes relief?",
    choices: [
      "Relief area",
      "Dropping zone only",
      "Nearest fairway point",
      "Reference area",
    ],
    answer: 0,
    citation: "Definition: Relief Area",
    explanation: "A relief area is the measured area where the player must drop a ball and where it must come to rest.",
  },
  {
    id: 26,
    category: "Section 6",
    points: 100,
    prompt: "A player\u2019s original ball may be lost outside a penalty area. What may the player play to save time?",
    choices: [
      "A provisional ball",
      "A substituted ball under free relief",
      "A second ball under Rule 20.1c",
      "A practice ball",
    ],
    answer: 0,
    citation: "Rule 18.3; Rule 6.3",
    explanation: "A provisional ball may be played when the original ball might be lost outside a penalty area or out of bounds.",
  },
  {
    id: 27,
    category: "Section 7",
    points: 200,
    prompt: "A player searching in long grass bends grass enough to find the ball, but the lie is improved more than was reasonably necessary. What is the likely issue?",
    choices: [
      "The player may be penalized for improving conditions beyond fair search",
      "There can never be a penalty during search",
      "The ball is automatically lost",
      "The player must replay from the tee",
    ],
    answer: 0,
    citation: "Rule 7.1a; Rule 8.1a",
    explanation: "Players may take reasonable search actions, but going beyond what is fair can breach the Rules.",
  },
  {
    id: 28,
    category: "Section 2",
    points: 300,
    prompt: "If a road crosses the course and the Committee wants it treated as an integral object, where should that be stated?",
    choices: [
      "In the Local Rules",
      "Only verbally on the first tee",
      "On the player\u2019s scorecard after the round",
      "It cannot be stated",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Model Local Rules",
    explanation: "Committee decisions that affect status of objects should be clearly communicated through Local Rules.",
  },
  {
    id: 29,
    category: "Model Local Rules",
    points: 400,
    prompt: "Who decides whether a Model Local Rule is in effect for a competition?",
    choices: [
      "The Committee",
      "Each player",
      "The opponent only",
      "The caddie",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8",
    explanation: "The Committee is responsible for adopting and communicating Local Rules.",
  },
  {
    id: 30,
    category: "Clarifications",
    points: 500,
    prompt: "A player is uncertain whether a clarification changes a penalty. What should the player remember?",
    choices: [
      "Clarifications explain application; they should be read with the Rule",
      "Clarifications always remove penalties",
      "Clarifications are optional player advice",
      "Clarifications apply only to professionals",
    ],
    answer: 0,
    citation: "Official Clarifications",
    explanation: "Clarifications explain how Rules apply in particular circumstances and should be read with the underlying Rule.",
  },
  {
    id: 31,
    category: "Definitions",
    points: 100,
    prompt: "A white stake defining out of bounds interferes with a player\u2019s swing. What type of object is it?",
    choices: [
      "Boundary object",
      "Movable obstruction",
      "Immovable obstruction",
      "No play zone",
    ],
    answer: 0,
    citation: "Definition: Boundary Object",
    explanation: "Objects defining or showing out of bounds are boundary objects and are treated differently from obstructions.",
  },
  {
    id: 32,
    category: "Section 6",
    points: 200,
    prompt: "How many balls may a player normally have in play on a hole?",
    choices: [
      "One ball in play",
      "Two balls if the player announces them",
      "Any number if marked differently",
      "One ball plus a practice ball",
    ],
    answer: 0,
    citation: "Rule 6.3",
    explanation: "A player normally has one ball in play at a time, subject to specific Rules such as provisional balls.",
  },
  {
    id: 33,
    category: "Section 7",
    points: 300,
    prompt: "A ball is moved by an opponent during a search in match play. What normally happens?",
    choices: [
      "No penalty to the opponent and the ball is replaced",
      "Opponent gets the general penalty",
      "Player must play from the new spot",
      "Player loses the hole",
    ],
    answer: 0,
    citation: "Rule 7.4",
    explanation: "Accidental movement during search is generally not penalized and the ball is replaced.",
  },
  {
    id: 34,
    category: "Section 2",
    points: 400,
    prompt: "What is the Committee\u2019s role with dropping zones?",
    choices: [
      "Define and communicate them when a Local Rule authorizes their use",
      "Let players create them",
      "Use them only for out of bounds",
      "Require them for every relief situation",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Model Local Rules",
    explanation: "Dropping zones are Committee-defined relief areas used when authorized by a Local Rule.",
  },
  {
    id: 35,
    category: "Model Local Rules",
    points: 500,
    prompt: "A Local Rule conflicts with the Rules of Golf principles. What is the risk?",
    choices: [
      "It may be unauthorized",
      "It automatically overrides every Rule",
      "It applies only to professionals",
      "It applies only after the round",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8",
    explanation: "Local Rules must be consistent with the authorized guidance and Rules principles.",
  },
  {
    id: 36,
    category: "Clarifications",
    points: 100,
    prompt: "How often should a serious exam candidate check the current clarification document?",
    choices: [
      "Regularly, because updates may be issued",
      "Never after buying a book",
      "Only after failing an exam",
      "Only if a playing partner asks",
    ],
    answer: 0,
    citation: "R&A Rules Resources",
    explanation: "Clarification documents can be updated, so candidates should use the current version.",
  },
  {
    id: 37,
    category: "Definitions",
    points: 200,
    prompt: "A ball is in a rabbit scrape that affects the player\u2019s stance. Which defined condition is most likely involved?",
    choices: [
      "Animal hole",
      "Penalty area",
      "Loose impediment",
      "Embedded ball",
    ],
    answer: 0,
    citation: "Definition: Animal Hole",
    explanation: "An animal hole includes a hole dug by an animal and related loose material or disturbed ground.",
  },
  {
    id: 38,
    category: "Section 6",
    points: 300,
    prompt: "If a ball is lifted under a Rule that requires replacement, what should normally happen?",
    choices: [
      "The same ball must be replaced unless substitution is allowed",
      "Any ball may always be substituted",
      "The ball must be dropped within one club-length",
      "The player must replay from the previous spot",
    ],
    answer: 0,
    citation: "Rule 6.3b",
    explanation: "Substitution is only allowed when a Rule permits it; otherwise the original ball should be used.",
  },
  {
    id: 39,
    category: "Section 7",
    points: 400,
    prompt: "A player lifts a ball for identification and cleans mud from the entire ball when only a small mark needed checking. What is the likely ruling?",
    choices: [
      "Penalty may apply for cleaning more than necessary",
      "No penalty because identification was the purpose",
      "The player must substitute another ball",
      "The ball is lost",
    ],
    answer: 0,
    citation: "Rule 7.3",
    explanation: "When a ball is lifted only for identification, cleaning is limited to what is needed to identify it.",
  },
  {
    id: 40,
    category: "Section 2",
    points: 500,
    prompt: "Which setup issue should the Committee decide before play?",
    choices: [
      "Where tee markers and hole locations are placed",
      "Which player marks every scorecard",
      "Which club each player must use",
      "Whether players may ignore pace of play",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Course setup includes teeing areas and hole locations.",
  },
  {
    id: 41,
    category: "Model Local Rules",
    points: 100,
    prompt: "Where should Local Rules normally be made available?",
    choices: [
      "Scorecard, notice, rules sheet, website, or other player-facing communication",
      "Only in the Committee\u2019s private notes",
      "Only after the first ruling",
      "Only on request after the round",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8",
    explanation: "Players need access to Local Rules before or during play so they can apply them.",
  },
  {
    id: 42,
    category: "Clarifications",
    points: 200,
    prompt: "A clarification references a specific Rule number. What does that help the reader do?",
    choices: [
      "Connect the guidance to the controlling Rule",
      "Avoid reading the Rule",
      "Treat it as a Local Rule",
      "Apply it only in match play",
    ],
    answer: 0,
    citation: "Official Clarifications",
    explanation: "Clarifications are organized by Rule references so they can be used with the relevant Rule.",
  },
  {
    id: 43,
    category: "Definitions",
    points: 300,
    prompt: "Which term describes the spot where a player would take complete relief from interference without going nearer the hole?",
    choices: [
      "Nearest point of complete relief",
      "Point of maximum available relief",
      "Reference point for back-on-the-line relief",
      "Estimated point",
    ],
    answer: 0,
    citation: "Definition: Nearest Point of Complete Relief",
    explanation: "This reference point is used for many free-relief situations and must provide complete relief from the condition.",
  },
  {
    id: 44,
    category: "Section 6",
    points: 400,
    prompt: "A player holes out and then realizes they played a wrong ball in stroke play without correcting before teeing off on the next hole. What is the likely result?",
    choices: [
      "Disqualification",
      "One penalty stroke",
      "No penalty if score was lower",
      "General penalty only",
    ],
    answer: 0,
    citation: "Rule 6.3c",
    explanation: "Failure to correct playing a wrong ball in stroke play before the required time leads to disqualification.",
  },
  {
    id: 45,
    category: "Section 7",
    points: 500,
    prompt: "When is a ball found for Rules purposes?",
    choices: [
      "When it is identified as the player\u2019s ball within the search time",
      "When anyone sees any ball in the area",
      "When the player believes it is probably theirs",
      "Only when the player touches it",
    ],
    answer: 0,
    citation: "Definition: Lost; Rule 7",
    explanation: "A ball must be found and identified within the allowed search time.",
  },
  {
    id: 46,
    category: "Section 2",
    points: 100,
    prompt: "A Committee fails to define an unusual course feature. What is the likely practical problem?",
    choices: [
      "Players may be uncertain which Rule applies",
      "The feature automatically becomes out of bounds",
      "All players get free relief",
      "The competition is automatically cancelled",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Clear definitions and markings help avoid uncertainty and inconsistent rulings.",
  },
  {
    id: 47,
    category: "Model Local Rules",
    points: 200,
    prompt: "A Committee wants to make a road an integral object. What is the best approach?",
    choices: [
      "Adopt a Local Rule stating that status",
      "Let each group decide",
      "Treat every road as out of bounds",
      "Require compulsory relief",
    ],
    answer: 0,
    citation: "Model Local Rules; Committee Procedures",
    explanation: "The Committee may define certain objects or conditions through Local Rules when appropriate.",
  },
  {
    id: 48,
    category: "Clarifications",
    points: 300,
    prompt: "If a Committee procedure has additional clarification, who is most likely to need it?",
    choices: [
      "Officials and Committees administering competitions",
      "Only spectators",
      "Only equipment manufacturers",
      "Only caddies",
    ],
    answer: 0,
    citation: "Official Clarifications; Committee Procedures",
    explanation: "Committee-related clarifications help those administering competitions apply the procedures consistently.",
  },
  {
    id: 49,
    category: "Definitions",
    points: 400,
    prompt: "A stone lying loose in a bunker is what type of item?",
    choices: [
      "Loose impediment",
      "Movable obstruction",
      "Integral object",
      "Boundary object",
    ],
    answer: 0,
    citation: "Definition: Loose Impediment",
    explanation: "A loose stone is a natural object and is generally a loose impediment.",
  },
  {
    id: 50,
    category: "Section 6",
    points: 500,
    prompt: "A player\u2019s ball breaks into pieces after a stroke. What is the normal ruling?",
    choices: [
      "The stroke does not count and the player plays another ball from where the stroke was made",
      "The player must play the largest piece",
      "The player gets one penalty stroke",
      "The ball is treated as lost",
    ],
    answer: 0,
    citation: "Rule 4.2b; Rule 6.3",
    explanation: "When a ball breaks into pieces after a stroke, the stroke does not count and another ball is played from the original spot.",
  },
  {
    id: 51,
    category: "Section 7",
    points: 100,
    prompt: "A player finds their ball after the three-minute search time has expired. What is the status of the original ball?",
    choices: [
      "Lost",
      "In play if found before another stroke",
      "Temporarily suspended",
      "A wrong ball",
    ],
    answer: 0,
    citation: "Definition: Lost; Rule 18.2",
    explanation: "A ball not found within the allowed search time is lost.",
  },
  {
    id: 52,
    category: "Section 2",
    points: 200,
    prompt: "What should the Committee do with temporary repairs on the course that should provide free relief?",
    choices: [
      "Define them as ground under repair",
      "Call them boundary objects",
      "Leave them unmarked and decide after play",
      "Treat them as penalty areas",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Definition: Ground Under Repair",
    explanation: "The Committee may define ground under repair for areas from which relief should be available.",
  },
  {
    id: 53,
    category: "Model Local Rules",
    points: 300,
    prompt: "A dropping zone is provided by Local Rule. What is it?",
    choices: [
      "A special relief area allowed or required by that Local Rule",
      "A place where practice strokes are made",
      "A place where all balls become holed",
      "A penalty area",
    ],
    answer: 0,
    citation: "Model Local Rules",
    explanation: "Dropping zones are Committee-created relief areas used under the terms of the Local Rule.",
  },
  {
    id: 54,
    category: "Clarifications",
    points: 400,
    prompt: "A player wants to rely on an old clarification they remember from years ago. What is the best exam habit?",
    choices: [
      "Check the current official clarification material",
      "Use memory only",
      "Ask another player to vote",
      "Ignore clarifications entirely",
    ],
    answer: 0,
    citation: "R&A Rules Resources",
    explanation: "For exam preparation, current official materials should be checked because clarifications can be updated.",
  },
  {
    id: 55,
    category: "Definitions",
    points: 500,
    prompt: "Which defined term covers an artificial path that cannot be moved?",
    choices: [
      "Immovable obstruction",
      "Loose impediment",
      "Integral object",
      "Boundary object",
    ],
    answer: 0,
    citation: "Definition: Immovable Obstruction",
    explanation: "A cart path or artificial path that cannot be moved easily is normally an immovable obstruction.",
  },
  {
    id: 56,
    category: "Section 6",
    points: 100,
    prompt: "A player tees a ball inside the teeing area, knocks it off the tee accidentally before making a stroke, and re-tees it. What is the ruling?",
    choices: [
      "No penalty",
      "One penalty stroke",
      "General penalty",
      "The ball must be played as it lies",
    ],
    answer: 0,
    citation: "Rule 6.2b",
    explanation: "A ball in the teeing area is not in play until a stroke is made, so it may be re-teed without penalty.",
  },
  {
    id: 57,
    category: "Section 7",
    points: 200,
    prompt: "A player searching for a ball in leaves removes loose leaves and reveals the ball. What is generally allowed?",
    choices: [
      "Reasonable actions to find and identify the ball",
      "Moving any growing branch without limit",
      "Pressing down vegetation to improve the stroke",
      "Replacing the ball with a cleaner ball",
    ],
    answer: 0,
    citation: "Rule 7.1",
    explanation: "Reasonable search actions are allowed, provided the player does not exceed what is fair search or improve conditions improperly.",
  },
  {
    id: 58,
    category: "Section 2",
    points: 300,
    prompt: "Why is consistency in course marking important?",
    choices: [
      "It supports fair and uniform application of the Rules",
      "It lets better players choose better relief",
      "It removes the need for referees",
      "It avoids all penalties",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Consistent marking helps all players apply the Rules in the same way.",
  },
  {
    id: 59,
    category: "Model Local Rules",
    points: 400,
    prompt: "A Model Local Rule has optional bracketed wording. What does that indicate?",
    choices: [
      "The Committee must choose or adapt details to fit the competition",
      "The player chooses after each stroke",
      "The wording is not part of the Rules",
      "It only applies in match play",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8",
    explanation: "Model Local Rules often require the Committee to specify details such as areas, dates, or measurements.",
  },
  {
    id: 60,
    category: "Clarifications",
    points: 500,
    prompt: "What is the safest way to write a study answer using a clarification?",
    choices: [
      "State the Rule reference, the clarification reference, and the practical ruling",
      "Quote a long passage from memory",
      "Use only the clarification title",
      "Avoid explaining the ruling",
    ],
    answer: 0,
    citation: "Official Clarifications",
    explanation: "Good study answers connect the Rule, any clarification, and the practical result.",
  },
  {
    id: 61,
    category: "Definitions",
    points: 100,
    prompt: "A player sees water on the fairway after heavy rain. Which defined term best fits water that is temporarily visible before or after the player takes a stance?",
    choices: [
      "Temporary water",
      "Penalty area",
      "Ground under repair",
      "Loose impediment",
    ],
    answer: 0,
    citation: "Definition: Temporary Water",
    explanation: "Temporary water is the relevant defined condition when water is temporarily visible on the course outside a penalty area.",
  },
  {
    id: 62,
    category: "Section 6",
    points: 200,
    prompt: "A player starts a hole from just outside the teeing area in stroke play and then corrects the mistake before starting the next hole. What is the normal consequence?",
    choices: [
      "General penalty and the corrected stroke counts",
      "No penalty because it was corrected",
      "Disqualification immediately",
      "One penalty stroke only",
    ],
    answer: 0,
    citation: "Rule 6.1b",
    explanation: "In stroke play, playing from outside the teeing area must be corrected and the player gets the general penalty.",
  },
  {
    id: 63,
    category: "Section 7",
    points: 300,
    prompt: "During a search, a player accidentally moves their own ball. What is the usual outcome under the search Rule?",
    choices: [
      "No penalty, and the ball must be replaced",
      "One penalty stroke and replace",
      "General penalty and play as it lies",
      "No penalty and play from the new spot",
    ],
    answer: 0,
    citation: "Rule 7.4",
    explanation: "There is normally no penalty for accidentally moving a ball while fairly searching, but it must be replaced.",
  },
  {
    id: 64,
    category: "Section 2",
    points: 400,
    prompt: "Who is responsible for deciding the boundaries of the course and marking penalty areas for a competition?",
    choices: [
      "The Committee",
      "Each player",
      "The marker",
      "The first group of the day",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Course setup responsibilities belong to the Committee, including boundaries and penalty area marking.",
  },
  {
    id: 65,
    category: "Model Local Rules",
    points: 500,
    prompt: "Model Local Rule E-5 is most closely connected with which situation?",
    choices: [
      "Alternative to stroke-and-distance for a ball lost outside a penalty area or out of bounds",
      "Free relief from a bunker every time",
      "Automatic preferred lies in all rough",
      "Practising on the course before a round",
    ],
    answer: 0,
    citation: "Model Local Rule E-5",
    explanation: "E-5 provides an alternative relief option for certain lost-ball or out-of-bounds situations when adopted.",
  },
  {
    id: 66,
    category: "Clarifications",
    points: 100,
    prompt: "A Clarification is best used when what is needed?",
    choices: [
      "Extra guidance on applying a Rule to a specific issue",
      "A replacement for the Rules of Golf",
      "Permission to ignore a Rule",
      "A way to avoid Committee decisions",
    ],
    answer: 0,
    citation: "Official Clarifications",
    explanation: "Clarifications help explain particular applications of the Rules but do not replace the Rules themselves.",
  },
  {
    id: 67,
    category: "Definitions",
    points: 200,
    prompt: "Which term describes the whole area of the course except the teeing area of the hole being played, all penalty areas, all bunkers, and the putting green of the hole being played?",
    choices: [
      "General area",
      "Through the green",
      "Course proper",
      "Relief area",
    ],
    answer: 0,
    citation: "Definition: General Area",
    explanation: "The general area is the default area of the course after excluding the specific areas listed in the definition.",
  },
  {
    id: 68,
    category: "Section 6",
    points: 300,
    prompt: "In match play, a player plays from outside the teeing area. What may the opponent do?",
    choices: [
      "Cancel the stroke and require replay from inside the teeing area",
      "Add two penalty strokes",
      "Declare the player disqualified",
      "Require the player to drop in the teeing area",
    ],
    answer: 0,
    citation: "Rule 6.1b",
    explanation: "In match play, the opponent may cancel a stroke made from outside the teeing area.",
  },
  {
    id: 69,
    category: "Section 7",
    points: 400,
    prompt: "A player moves sand while searching for a ball in a bunker and improves the lie after the ball is found. What must the player normally do?",
    choices: [
      "Re-create the original lie as nearly as possible",
      "Play it as improved without penalty",
      "Drop outside the bunker",
      "Declare the ball unplayable",
    ],
    answer: 0,
    citation: "Rule 7.1b",
    explanation: "If conditions are improved during a search, they may need to be restored as nearly as possible.",
  },
  {
    id: 70,
    category: "Section 2",
    points: 500,
    prompt: "Why should a Committee define the course accurately before a competition?",
    choices: [
      "So players know which Rules and relief options apply",
      "So players can choose their own relief areas",
      "So all penalty areas become optional",
      "So match play and stroke play use different boundaries",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Clear course definition helps players apply the correct Rules during the round.",
  },
  {
    id: 71,
    category: "Model Local Rules",
    points: 100,
    prompt: "If Model Local Rule E-5 is not adopted by the Committee, may a player use it anyway?",
    choices: [
      "No",
      "Yes, always",
      "Only in match play",
      "Only if the marker agrees",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8; Model Local Rules",
    explanation: "A Model Local Rule applies only when the Committee has adopted it.",
  },
  {
    id: 72,
    category: "Clarifications",
    points: 200,
    prompt: "If a Rules question is answered directly by the Rule text, what should be consulted first?",
    choices: [
      "The relevant Rule",
      "Social media comments",
      "Only the Clarifications",
      "A player vote",
    ],
    answer: 0,
    citation: "Official Clarifications introduction",
    explanation: "Clarifications are additional guidance; the Rules themselves remain the primary source.",
  },
  {
    id: 73,
    category: "Definitions",
    points: 300,
    prompt: "A ball is resting against a movable rake beside a bunker. What is the rake under the Rules?",
    choices: [
      "Movable obstruction",
      "Loose impediment",
      "Integral object",
      "Boundary object",
    ],
    answer: 0,
    citation: "Definition: Obstruction",
    explanation: "A manufactured object that can be moved with reasonable effort and without damaging the course is normally a movable obstruction.",
  },
  {
    id: 74,
    category: "Section 6",
    points: 400,
    prompt: "When does play of a hole normally begin?",
    choices: [
      "When the player makes a stroke to start the hole",
      "When the player arrives at the tee",
      "When the group ahead leaves the green",
      "When the scorecard is marked",
    ],
    answer: 0,
    citation: "Rule 6.1",
    explanation: "A hole begins when the player makes a stroke to start that hole.",
  },
  {
    id: 75,
    category: "Section 7",
    points: 500,
    prompt: "A player finds a ball but is not sure it is theirs. What may the player do?",
    choices: [
      "Mark and lift it to identify it",
      "Kick it over without marking",
      "Clean it fully and replace it anywhere",
      "Substitute a new ball",
    ],
    answer: 0,
    citation: "Rule 7.3",
    explanation: "A player may lift a ball to identify it after first marking the spot, but cleaning is limited to what is needed.",
  },
  {
    id: 76,
    category: "Section 2",
    points: 100,
    prompt: "A Committee wants to mark an area where play is prohibited. What should it define the area as?",
    choices: [
      "A no play zone connected to an abnormal course condition or penalty area",
      "A bunker",
      "A loose impediment area",
      "An automatic free-drop zone only",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Definition: No Play Zone",
    explanation: "A no play zone must be defined as part of another condition such as an abnormal course condition or penalty area.",
  },
  {
    id: 77,
    category: "Model Local Rules",
    points: 200,
    prompt: "Preferred lies are usually implemented through which mechanism?",
    choices: [
      "A Model Local Rule adopted by the Committee",
      "A player\u2019s choice at any time",
      "An automatic Rule whenever the fairway is wet",
      "A decision by the marker after each shot",
    ],
    answer: 0,
    citation: "Model Local Rule E-3",
    explanation: "Preferred lies require Committee adoption and defined terms such as the area and size of relief.",
  },
  {
    id: 78,
    category: "Clarifications",
    points: 300,
    prompt: "A clarification about practice before a stroke-play round would most likely relate to which Rule area?",
    choices: [
      "Rule 5.2",
      "Rule 18.3",
      "Rule 6.1",
      "Rule 13.2",
    ],
    answer: 0,
    citation: "Clarification 5.2b/3",
    explanation: "Recent clarifications include guidance on practice on the course before a stroke-play round.",
  },
  {
    id: 79,
    category: "Definitions",
    points: 400,
    prompt: "A branch that has fallen from a tree is lying near a player\u2019s ball. What is it?",
    choices: [
      "Loose impediment",
      "Movable obstruction",
      "Ground under repair",
      "Abnormal course condition",
    ],
    answer: 0,
    citation: "Definition: Loose Impediment",
    explanation: "A detached natural object such as a fallen branch is a loose impediment unless it is fixed, growing, embedded, or sticking to the ball.",
  },
  {
    id: 80,
    category: "Section 6",
    points: 500,
    prompt: "A player accidentally plays a wrong ball from the fairway in stroke play. What must the player generally do?",
    choices: [
      "Correct the mistake by playing the right ball and add the general penalty",
      "Continue with the wrong ball without penalty",
      "Replay from the tee with one penalty stroke",
      "Drop where the wrong ball was played",
    ],
    answer: 0,
    citation: "Rule 6.3c",
    explanation: "Playing a wrong ball in stroke play must be corrected, normally with the general penalty.",
  },
  {
    id: 81,
    category: "Section 7",
    points: 100,
    prompt: "Before lifting a ball for identification, what should the player do?",
    choices: [
      "Mark the spot",
      "Announce a provisional ball",
      "Take lateral relief",
      "Ask the Committee for permission every time",
    ],
    answer: 0,
    citation: "Rule 7.3",
    explanation: "The spot should be marked before the ball is lifted for identification.",
  },
  {
    id: 82,
    category: "Section 2",
    points: 200,
    prompt: "Before a competition, the Committee should consider whether Local Rules are needed for what purpose?",
    choices: [
      "To address course conditions or competition needs consistently with the Rules",
      "To let players ignore difficult Rules",
      "To remove all penalties",
      "To change stroke play into match play",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Section 8",
    explanation: "Local Rules may be adopted for appropriate course or competition conditions, but must be consistent with the Rules.",
  },
  {
    id: 83,
    category: "Model Local Rules",
    points: 300,
    prompt: "A Committee wants to allow relief from seams of cut turf. What should it use?",
    choices: [
      "An appropriate Model Local Rule",
      "A verbal announcement only after disputes arise",
      "A player-by-player agreement",
      "The lost ball Rule",
    ],
    answer: 0,
    citation: "Model Local Rules",
    explanation: "Model Local Rules provide approved wording and structure for specific local conditions.",
  },
  {
    id: 84,
    category: "Clarifications",
    points: 400,
    prompt: "Clarifications are incorporated into digital Rules materials for what purpose?",
    choices: [
      "To keep guidance accessible with the Rules",
      "To replace the Committee Procedures",
      "To remove penalties",
      "To make Local Rules automatic",
    ],
    answer: 0,
    citation: "R&A Rules Resources: Additional Clarifications",
    explanation: "Digital Rules materials may include additional clarifications so users can find current guidance.",
  },
  {
    id: 85,
    category: "Definitions",
    points: 500,
    prompt: "Which phrase describes where a ball must be dropped and come to rest when a player takes relief?",
    choices: [
      "Relief area",
      "Dropping zone only",
      "Nearest fairway point",
      "Reference area",
    ],
    answer: 0,
    citation: "Definition: Relief Area",
    explanation: "A relief area is the measured area where the player must drop a ball and where it must come to rest.",
  },
  {
    id: 86,
    category: "Section 6",
    points: 100,
    prompt: "A player\u2019s original ball may be lost outside a penalty area. What may the player play to save time?",
    choices: [
      "A provisional ball",
      "A substituted ball under free relief",
      "A second ball under Rule 20.1c",
      "A practice ball",
    ],
    answer: 0,
    citation: "Rule 18.3; Rule 6.3",
    explanation: "A provisional ball may be played when the original ball might be lost outside a penalty area or out of bounds.",
  },
  {
    id: 87,
    category: "Section 7",
    points: 200,
    prompt: "A player searching in long grass bends grass enough to find the ball, but the lie is improved more than was reasonably necessary. What is the likely issue?",
    choices: [
      "The player may be penalized for improving conditions beyond fair search",
      "There can never be a penalty during search",
      "The ball is automatically lost",
      "The player must replay from the tee",
    ],
    answer: 0,
    citation: "Rule 7.1a; Rule 8.1a",
    explanation: "Players may take reasonable search actions, but going beyond what is fair can breach the Rules.",
  },
  {
    id: 88,
    category: "Section 2",
    points: 300,
    prompt: "If a road crosses the course and the Committee wants it treated as an integral object, where should that be stated?",
    choices: [
      "In the Local Rules",
      "Only verbally on the first tee",
      "On the player\u2019s scorecard after the round",
      "It cannot be stated",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Model Local Rules",
    explanation: "Committee decisions that affect status of objects should be clearly communicated through Local Rules.",
  },
  {
    id: 89,
    category: "Model Local Rules",
    points: 400,
    prompt: "Who decides whether a Model Local Rule is in effect for a competition?",
    choices: [
      "The Committee",
      "Each player",
      "The opponent only",
      "The caddie",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8",
    explanation: "The Committee is responsible for adopting and communicating Local Rules.",
  },
  {
    id: 90,
    category: "Clarifications",
    points: 500,
    prompt: "A player is uncertain whether a clarification changes a penalty. What should the player remember?",
    choices: [
      "Clarifications explain application; they should be read with the Rule",
      "Clarifications always remove penalties",
      "Clarifications are optional player advice",
      "Clarifications apply only to professionals",
    ],
    answer: 0,
    citation: "Official Clarifications",
    explanation: "Clarifications explain how Rules apply in particular circumstances and should be read with the underlying Rule.",
  },
  {
    id: 91,
    category: "Definitions",
    points: 100,
    prompt: "A white stake defining out of bounds interferes with a player\u2019s swing. What type of object is it?",
    choices: [
      "Boundary object",
      "Movable obstruction",
      "Immovable obstruction",
      "No play zone",
    ],
    answer: 0,
    citation: "Definition: Boundary Object",
    explanation: "Objects defining or showing out of bounds are boundary objects and are treated differently from obstructions.",
  },
  {
    id: 92,
    category: "Section 6",
    points: 200,
    prompt: "How many balls may a player normally have in play on a hole?",
    choices: [
      "One ball in play",
      "Two balls if the player announces them",
      "Any number if marked differently",
      "One ball plus a practice ball",
    ],
    answer: 0,
    citation: "Rule 6.3",
    explanation: "A player normally has one ball in play at a time, subject to specific Rules such as provisional balls.",
  },
  {
    id: 93,
    category: "Section 7",
    points: 300,
    prompt: "A ball is moved by an opponent during a search in match play. What normally happens?",
    choices: [
      "No penalty to the opponent and the ball is replaced",
      "Opponent gets the general penalty",
      "Player must play from the new spot",
      "Player loses the hole",
    ],
    answer: 0,
    citation: "Rule 7.4",
    explanation: "Accidental movement during search is generally not penalized and the ball is replaced.",
  },
  {
    id: 94,
    category: "Section 2",
    points: 400,
    prompt: "What is the Committee\u2019s role with dropping zones?",
    choices: [
      "Define and communicate them when a Local Rule authorizes their use",
      "Let players create them",
      "Use them only for out of bounds",
      "Require them for every relief situation",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2; Model Local Rules",
    explanation: "Dropping zones are Committee-defined relief areas used when authorized by a Local Rule.",
  },
  {
    id: 95,
    category: "Model Local Rules",
    points: 500,
    prompt: "A Local Rule conflicts with the Rules of Golf principles. What is the risk?",
    choices: [
      "It may be unauthorized",
      "It automatically overrides every Rule",
      "It applies only to professionals",
      "It applies only after the round",
    ],
    answer: 0,
    citation: "Committee Procedures Section 8",
    explanation: "Local Rules must be consistent with the authorized guidance and Rules principles.",
  },
  {
    id: 96,
    category: "Clarifications",
    points: 100,
    prompt: "How often should a serious exam candidate check the current clarification document?",
    choices: [
      "Regularly, because updates may be issued",
      "Never after buying a book",
      "Only after failing an exam",
      "Only if a playing partner asks",
    ],
    answer: 0,
    citation: "R&A Rules Resources",
    explanation: "Clarification documents can be updated, so candidates should use the current version.",
  },
  {
    id: 97,
    category: "Definitions",
    points: 200,
    prompt: "A ball is in a rabbit scrape that affects the player\u2019s stance. Which defined condition is most likely involved?",
    choices: [
      "Animal hole",
      "Penalty area",
      "Loose impediment",
      "Embedded ball",
    ],
    answer: 0,
    citation: "Definition: Animal Hole",
    explanation: "An animal hole includes a hole dug by an animal and related loose material or disturbed ground.",
  },
  {
    id: 98,
    category: "Section 6",
    points: 300,
    prompt: "If a ball is lifted under a Rule that requires replacement, what should normally happen?",
    choices: [
      "The same ball must be replaced unless substitution is allowed",
      "Any ball may always be substituted",
      "The ball must be dropped within one club-length",
      "The player must replay from the previous spot",
    ],
    answer: 0,
    citation: "Rule 6.3b",
    explanation: "Substitution is only allowed when a Rule permits it; otherwise the original ball should be used.",
  },
  {
    id: 99,
    category: "Section 7",
    points: 400,
    prompt: "A player lifts a ball for identification and cleans mud from the entire ball when only a small mark needed checking. What is the likely ruling?",
    choices: [
      "Penalty may apply for cleaning more than necessary",
      "No penalty because identification was the purpose",
      "The player must substitute another ball",
      "The ball is lost",
    ],
    answer: 0,
    citation: "Rule 7.3",
    explanation: "When a ball is lifted only for identification, cleaning is limited to what is needed to identify it.",
  },
  {
    id: 100,
    category: "Section 2",
    points: 500,
    prompt: "Which setup issue should the Committee decide before play?",
    choices: [
      "Where tee markers and hole locations are placed",
      "Which player marks every scorecard",
      "Which club each player must use",
      "Whether players may ignore pace of play",
    ],
    answer: 0,
    citation: "Committee Procedures Section 2",
    explanation: "Course setup includes teeing areas and hole locations.",
  },
];
